[src]
include = ["test/functional/**", "contrib/devtools/**"]
exclude = [
    "test/functional/data/**",
    "test/functional/mocks/**",
]

[environment]
root = ["test/functional"]

[rules]
not-subscriptable = "ignore"
invalid-argument-type = "ignore"
unresolved-attribute = "ignore"
unsupported-operator = "ignore"
invalid-assignment = "ignore"
not-iterable = "ignore"
possibly-missing-attribute = "ignore"
deprecated = "ignore"
invalid-method-override = "ignore"
unused-ignore-comment = "ignore"
too-many-positional-arguments = "ignore"
invalid-return-type = "ignore"
