[src]
include = ["test/functional/**", "contrib/devtools/**"]
exclude = [
    "test/functional/data/**",
    "test/functional/mocks/**",
]

[environment]
root = ["test/functional"]

[rules]
possibly-missing-attribute = "ignore"
deprecated = "ignore"
invalid-method-override = "ignore"
unused-ignore-comment = "ignore"
too-many-positional-arguments = "ignore"
invalid-return-type = "ignore"
