on:
  push:
    branches: master
  pull_request:

jobs:
  benchmark_base_branch:
    name: Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install hyperfine clang-15 ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap-sdt-dev libminiupnpc-dev libnatpmp-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev -y
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Build bitcoind
        run: |
          ./autogen.sh && CC=clang-15 CXX=clang++-15 ./configure --disable-tests --disable-wallet --without-gui --disable-bench --disable-fuzz-binary && make clean && make -j $(nproc) -C src bitcoind
      - name: Bencher
        run: |
          bencher run \
          --project core-test \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ubuntu-latest \
          --adapter shell_hyperfine \
          --err \
          --file results.json \
          "hyperfine --runs 2 --export-json results.json --time-unit second './src/bitcoind --stopatheight=5000'"
