on:
  issues:
    types: [opened, reopened]

name: "Vouch - Check Issue"

permissions:
  contents: read
  issues: write

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: mitchellh/vouch/action/check-issue@0e11a71bba23218a284d3ecca162e75a110fd7e3 # v1.3.0
        with:
          issue-number: ${{ github.event.issue.number }}
          auto-close: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
