on:
  discussion_comment:
    types: [created]

name: "Vouch - Manage by Discussion"

concurrency:
  group: vouch-manage
  cancel-in-progress: false

permissions:
  contents: write
  discussions: write
  pull-requests: write

jobs:
  manage:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - uses: mitchellh/vouch/action/manage-by-discussion@0e11a71bba23218a284d3ecca162e75a110fd7e3 # v1.3.0
        with:
          discussion-number: ${{ github.event.discussion.number }}
          comment-node-id: ${{ github.event.comment.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
